from __future__ import annotations

"""Evaluate one saved default-setting policy against Reflex on a separate pool.

Reports workload-level paired statistics conditional on the saved checkpoint.
The win score gives half credit to ties. Equivalence margins and paired-t
sensitivity at the observed effect are exploratory. Current manuscript figures
and the complete comparison family are generated by scripts.sncs_report.
"""

import argparse
import csv
from pathlib import Path
from typing import Dict, List

import numpy as np
import torch
torch.set_num_threads(1)
from scipy import stats

from src.config import load_config
from src.reflex_agent import build_reflex_agent
from src.rl.agent import RLPolicyAgent, load_policy
from src.runner import run_many_episodes

BOOT_SEED = 20260418
N_BOOT = 10000


def _utils(cfg, factory, seeds) -> np.ndarray:
    ms = run_many_episodes(cfg=cfg, agent_factory=factory, seeds=seeds, include_uncapped=False)
    return np.array([m.total_utility for m in ms], dtype=np.float64)


def _iqm(x: np.ndarray) -> float:
    return float(stats.trim_mean(x, 0.25))


def _boot_ci(x: np.ndarray, stat, n_boot=N_BOOT, alpha=0.05):
    rng = np.random.default_rng(BOOT_SEED)
    idx = rng.integers(0, len(x), size=(n_boot, len(x)))
    vals = np.array([stat(x[i]) for i in idx])
    return float(np.quantile(vals, alpha / 2)), float(np.quantile(vals, 1 - alpha / 2))


def _paired_boot_ci(d: np.ndarray, stat, n_boot=N_BOOT, alpha=0.05):
    rng = np.random.default_rng(BOOT_SEED)
    idx = rng.integers(0, len(d), size=(n_boot, len(d)))
    vals = np.array([stat(d[i]) for i in idx])
    return float(np.quantile(vals, alpha / 2)), float(np.quantile(vals, 1 - alpha / 2))


def _prob_improvement(rl: np.ndarray, rf: np.ndarray) -> float:
    """Paired win score: P(RL > Reflex) + 0.5 P(RL = Reflex)."""
    wins = (rl > rf).astype(float) + 0.5 * (rl == rf).astype(float)
    return float(wins.mean())


def _paired_t_power(dz: float, n: int, alpha=0.05) -> float:
    """Two-sided paired t-test power at standardized effect dz, sample size n."""
    df = n - 1
    ncp = dz * np.sqrt(n)
    t_crit = stats.t.ppf(1 - alpha / 2, df)
    # P(reject) = P(T' > t_crit) + P(T' < -t_crit) under noncentral t.
    return float(
        (1 - stats.nct.cdf(t_crit, df, ncp)) + stats.nct.cdf(-t_crit, df, ncp)
    )


def _n_for_power(dz: float, target=0.80, alpha=0.05) -> int:
    if dz == 0:
        return 10**9
    for n in range(4, 5000):
        if _paired_t_power(dz, n, alpha) >= target:
            return n
    return 5000


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=None)
    parser.add_argument("--checkpoint", type=Path,
                        default=Path("results/phase5/rl_seed7/policy_best_by_val.pt"))
    parser.add_argument("--seed-start", type=int, default=1000)
    parser.add_argument("--seed-stop", type=int, default=1250)
    parser.add_argument("--margins", nargs="*", type=float, default=[3.0, 5.0, 10.0])
    parser.add_argument("--out", type=Path, default=Path("results/hardening/power_rliable.csv"))
    args = parser.parse_args()

    cfg = load_config(args.config) if args.config else load_config()
    seeds = list(range(args.seed_start, args.seed_stop))

    # Disjointness guard (integrity): the extended pool must not touch any
    # training/validation/test seed.
    train = set(cfg.rl.training_seeds); val = set(cfg.rl.validation_seeds); test = set(cfg.rl.test_seeds)
    overlap = set(seeds) & (train | val | test)
    if overlap:
        raise SystemExit(f"extended pool overlaps existing pools: {sorted(overlap)[:5]}...")
    print(f"Extended held-out pool: {seeds[0]}..{seeds[-1]} (n={len(seeds)}), "
          f"disjoint from train/val/test. config={cfg.meta.get('config_name')}\n")

    policy = load_policy(cfg, args.checkpoint)
    rl = _utils(cfg, lambda c: RLPolicyAgent(c, policy, deterministic=True), seeds)
    rf = _utils(cfg, build_reflex_agent, seeds)
    d = rl - rf
    n = len(d)

    # ---- point + interval estimates ----
    print("=== rliable-style estimates (total utility) ===")
    for name, x in [("RL", rl), ("Reflex", rf)]:
        m_lo, m_hi = _boot_ci(x, np.mean)
        i_lo, i_hi = _boot_ci(x, _iqm)
        print(f"{name:<8} mean {x.mean():7.3f} [{m_lo:7.3f},{m_hi:7.3f}]  "
              f"IQM {_iqm(x):7.3f} [{i_lo:7.3f},{i_hi:7.3f}]")

    # ---- paired tests ----
    print("\n=== paired tests (RL - Reflex) ===")
    md_lo, md_hi = _paired_boot_ci(d, np.mean)
    print(f"mean diff {d.mean():+.4f} [{md_lo:+.4f},{md_hi:+.4f}]  std {d.std(ddof=1):.4f}")
    try:
        w_p = stats.wilcoxon(rl, rf).pvalue
    except ValueError:
        w_p = float("nan")
    t_res = stats.ttest_rel(rl, rf)
    print(f"Wilcoxon p = {w_p:.3e} | paired t p = {t_res.pvalue:.3e} "
          f"(t={t_res.statistic:.3f})")
    print(f"wins RL>Reflex {int((d>0).sum())}/{n}, RL<Reflex {int((d<0).sum())}, "
          f"ties {int((d==0).sum())}")

    # ---- probability of improvement ----
    poi = _prob_improvement(rl, rf)
    poi_lo, poi_hi = _paired_boot_ci(d, lambda dd: ((dd > 0).mean() + 0.5 * (dd == 0).mean()))
    print(f"\nPaired win score (half-credit for ties) = {poi:.3f} [{poi_lo:.3f},{poi_hi:.3f}] "
          f"(0.5 = balanced paired score)")

    # ---- TOST equivalence ----
    print("\n=== Exploratory TOST (RL vs Reflex), 90% CI within +/- margin ? ===")
    se = d.std(ddof=1) / np.sqrt(n)
    ci90_lo = d.mean() - stats.t.ppf(0.95, n - 1) * se
    ci90_hi = d.mean() + stats.t.ppf(0.95, n - 1) * se
    print(f"90% CI of mean diff: [{ci90_lo:+.3f}, {ci90_hi:+.3f}]")
    for margin in args.margins:
        equiv = (ci90_lo > -margin) and (ci90_hi < margin)
        print(f"  margin +/-{margin:>5.1f}: equivalent = {equiv}")

    # ---- power analysis ----
    dz = d.mean() / d.std(ddof=1)
    print("\n=== effect-size-based sensitivity (paired t, alpha=0.05 two-sided) ===")
    print(f"observed standardized effect dz = {dz:+.4f}")
    print(f"power at n={n}: {_paired_t_power(abs(dz), n):.3f}")
    print(f"power at n=50 : {_paired_t_power(abs(dz), 50):.3f}")
    print(f"n for 80% power at this effect: {_n_for_power(abs(dz))}")

    # ---- performance profiles ----
    taus = np.linspace(min(rl.min(), rf.min()), max(rl.max(), rf.max()), 30)
    rows = [{"tau": round(t, 3),
             "rl_frac_ge": float((rl >= t).mean()),
             "reflex_frac_ge": float((rf >= t).mean())} for t in taus]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", newline="", encoding="utf-8") as h:
        w = csv.DictWriter(h, fieldnames=["tau", "rl_frac_ge", "reflex_frac_ge"])
        w.writeheader(); w.writerows(rows)
    # also dump per-seed
    with args.out.with_name("power_rliable_perseed.csv").open("w", newline="", encoding="utf-8") as h:
        w = csv.DictWriter(h, fieldnames=["seed", "rl_util", "reflex_util", "diff"])
        w.writeheader()
        for s, a, b in zip(seeds, rl, rf):
            w.writerow({"seed": s, "rl_util": round(a, 4), "reflex_util": round(b, 4),
                        "diff": round(a - b, 4)})
    print(f"\nwrote {args.out} and per-seed CSV")

    print("\nInterpretation: the mean difference, win score and exploratory equivalence "
          "margins answer different questions. A detectable difference can coexist "
          "with equivalence within a sufficiently broad margin. These are workload-level "
          "results for one saved policy, not training-run inference.")


if __name__ == "__main__":
    main()
